=== 0rganics/homebrew/schema.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"version": "1.1.1",
	"type": "object",
	"description": "Homebrew for 5etools. Should include arrays titled similarly to the main site data, e.g. `spell` or `class`",
	"definitions": {
		"entry": {
			"$id": "/Entry",
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/entry.json"
		},
		"bookSource": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string"
				},
				"source": {
					"type": "string"
				}
			},
			"required": [
				"id",
				"source"
			]
		}
	},
	"properties": {
		"_meta": {
			"description": "Metadata for the included data arrays",
			"type": "object",
			"properties": {
				"sources": {
					"type": "array",
					"items": {
						"type": "object",
						"description": "A set of properties describing a \"source.\" A source could be, for example, a homebrew PDF, book, or blog post.",
						"properties": {
							"json": {
								"type": "string",
								"description": "An identifying string, as seen in the JSON in \"source\" fields."
							},
							"abbreviation": {
								"type": "string",
								"description": "Abbreviated form of the source, to display on the site."
							},
							"full": {
								"type": "string",
								"description": "Full title of the source, to display on the site."
							},
							"authors": {
								"type": "array",
								"description": "A list of authors who created the homebrew source.",
								"items": {
									"type": "string",
									"description": "Author name."
								}
							},
							"convertedBy": {
								"type": "array",
								"description": "An optional list of people who contributed to converting the source to 5etools format.",
								"items": {
									"type": "string",
									"description": "Contributor name."
								}
							},
							"version": {
								"type": "string",
								"description": "The source version, e.g. \"1.2.3\"."
							},
							"url": {
								"type": "string",
								"description": "A direct link to the source, if available in web form or on a store."
							},
							"targetSchema": {
								"type": "string",
								"description": "The target schema version in 5etools, e.g. \"1.2.3\"."
							}
						}
					}
				},
				"actions": {
					"type": "object",
					"description": "Object keys are Action names, which can referenced using {@action <key>} (case sensitive)"
				},
				"skills": {
					"type": "object",
					"description": "Object keys are Skill names, which can referenced using {@skill <key>} (case sensitive)"
				},
				"senses": {
					"type": "object",
					"description": "Object keys are Sense names, which can referenced using {@sense <key>} (case insensitive)"
				},
				"spellSchools": {
					"type": "object",
					"description": "Object names are spell school abbreviations; values should be objects with `\"full\"`` (used in the main entry, e.g. \"Evocation\") and `\"short\"` (used in the list view, e.g. `\"Evoc.\"`) key/values."
				},
				"spellDistanceUnits": {
					"type": "object",
					"description": "Object names are spell distance units; values should be objects with optional `\"singular\"`` (singular form of the unit, e.g. \"foot\" for the singular of \"feet\"--if unspecified, a trailing \"s\" is removed from the plural version, if it exists, and the result is used as the singular form) and `\"feetPerUnit\"` (e.g. for a \"yards\" custom unit, this would be `3`, as there are three feet in a yard) key/values."
				},
				"optionalFeatureTypes": {
					"type": "object",
					"description": "Object names are optional feature \"type\" shorthands (e.g. \"EI\" for \"Eldritch Invocation\" which will be displayed in the list view as a sortable column"
				},
				"dateAdded": {
					"type": "integer",
					"description": "The epoch timestamp (in seconds) when the homebrew was added to the repository. Not guaranteed to be anywhere near accurate."
				},
				"dependencies": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			}
		},
		"adventure": {
			"type": "array",
			"items": {
				"allOf": [
					{
						"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/adventures.json#/properties/adventure/items"
					},
					{
						"$ref": "#/definitions/bookSource"
					}
				]
			}
		},
		"adventureData": {
			"type": "array",
			"items": {
				"allOf": [
					{
						"$ref": "#/definitions/bookSource"
					},
					{
						"properties": {
							"data": {
								"type": "array",
								"items": {
									"$ref": "#/definitions/entry"
								}
							}
						}
					}
				]
			}
		},
		"book": {
			"type": "array",
			"items": {
				"allOf": [
					{
						"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/adventures.json#/properties/adventure/items"
					},
					{
						"$ref": "#/definitions/bookSource"
					}
				]
			}
		},
		"bookData": {
			"type": "array",
			"items": {
				"allOf": [
					{
						"$ref": "#/definitions/bookSource"
					},
					{
						"properties": {
							"data": {
								"type": "array",
								"items": {
									"$ref": "#/definitions/entry"
								}
							}
						}
					}
				]
			}
		},
		"class": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/class/class.json#/properties/class"
		},
		"subclass": {
			"type": "array",
			"items": {
				"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/class/class.json#/definitions/subclass"
			}
		},
		"spell": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/spells/spells.json#/properties/spell"
		},
		"item": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/items.json#/properties/item"
		},
		"itemGroup": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/items.json#properties/itemGroup"
		},
		"basicitem": {
			"description": "Not supported",
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/basicitems.json#properties/basicitem"
		},
		"itemProperty": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/basicitems.json#properties/itemProperty"
		},
		"itemType": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/basicitems.json#properties/itemType"
		},
		"variant": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/magicvariants.json#properties/variant"
		},
		"background": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/backgrounds.json#/properties/background"
		},
		"condition": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/conditionsdiseases.json#/properties/condition"
		},
		"disease": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/conditionsdiseases.json#/properties/disease"
		},
		"deity": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/deities.json#/properties/deity"
		},
		"cult": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/cultsboons.json#/properties/cult"
		},
		"boon": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/cultsboons.json#/properties/boon"
		},
		"encounter": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/encounters.json#/properties/encounter"
		},
		"feat": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/feats.json#/properties/feat"
		},
		"name": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/names.json#/properties/name"
		},
		"object": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/objects.json#/properties/object"
		},
		"psionic": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/psionics.json#/properties/psionic"
		},
		"race": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/races.json#/properties/race"
		},
		"reward": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/rewards.json#/properties/reward"
		},
		"ship": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/ships.json#/properties/ship"
		},
		"table": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/tables.json#/properties/table"
		},
		"trap": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/trapshazards.json#/properties/trap"
		},
		"hazard": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/trapshazards.json#/properties/hazard"
		},
		"optionalfeature": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/optionalfeatures.json#properties/optionalfeature"
		},
		"variantrule": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/variantrules.json#properties/variantrule"
		},
		"legendaryGroup": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/bestiary/meta.json#/properties/legendaryGroup"
		},
		"language": {
			"$ref": "https://gitcdn.link/repo/TheGiddyLimit/TheGiddyLimit.github.io/master/test/schema/bestiary/meta.json#/properties/language"
		},
		"monster": {
			"type": "array",
			"items": {
				"type": "object",
				"description": "Creature Data"
			}
		}
	}
}

=== 0rganics/homebrew/collection/Sesserdrix; Spelljammer - More Adventures in Space.json
{
  "_meta": {
    "sources": [
      {
        "json": "SJMAiS",
        "abbreviation": "SJMAiS",
        "full": "Spelljammer - More Adventures in Space",
        "authors": [
          "Sesserdrix"
        ],
        "convertedBy": [
          "Surge"
        ],
        "url": "https://www.dropbox.com/sh/3c88jrhy1t7gyql/AACS63QaKFCCrBn_-cxRVHBda",
        "version": "0.94",
        "targetSchema": "1.0.0"
      }
    ],
    "dateAdded": 1616108022,
    "dateLastModified": 1616108022
  },
  "itemType": [
    {
      "abbreviation": "SJW",
      "source": "SJMAiS",
      "name": "Spelljammer Weapon",
      "entries": [
        {
          "type": "entries",
          "name": "Spelljammer Weapon",
          "entries": [
            "This weapon must be mounted in a Spelljammer to be operated. It deals mega damage and may only target other Spelljammer vessels or mega-sized creatures."
          ]
        }
      ]
    }
  ],
  "itemProperty": [
    {
      "abbreviation": "BF2",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Backfire 2",
          "entries": [
            "When you make an attack with this weapon, if the unmodified die roll is equal or less than 2, the weapon breaks after the attack. The weapon remains broken until the Gunner uses their action to repair it."
          ]
        }
      ]
    },
    {
      "abbreviation": "BF3",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Backfire 3",
          "entries": [
            "When you make an attack with this weapon, if the unmodified die roll is equal or less than 3, the weapon breaks after the attack. The weapon remains broken until the Gunner uses their action to repair it."
          ]
        }
      ]
    },
    {
      "abbreviation": "BF4",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Backfire 4",
          "entries": [
            "When you make an attack with this weapon, if the unmodified die roll is equal or less than 4, the weapon breaks after the attack. The weapon remains broken until the Gunner uses their action to repair it."
          ]
        }
      ]
    },
    {
      "abbreviation": "CRW1",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 1",
          "entries": [
            "This weapon requires 1 additional crew member to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "CRW2",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 2",
          "entries": [
            "This weapon requires 2 additional crew members to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "CRW3",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 3",
          "entries": [
            "This weapon requires 3 additional crew members to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "CRW4",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 4",
          "entries": [
            "This weapon requires 4 additional crew members to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "CRW5",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 5",
          "entries": [
            "This weapon requires 5 additional crew members to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "CRW6",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 6",
          "entries": [
            "This weapon requires 6 additional crew members to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "CRW8",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Crew 8",
          "entries": [
            "This weapon requires 8 additional crew members to operate."
            ]
        }
      ]
    },
    {
      "abbreviation": "FX",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Fixed",
          "entries": [
            "When mounted, this weapon is affixed to face a certain direction. It can only make attacks against targets within a 90-degree cone in the direction it is facing."
            ]
        }
      ]
    },
    {
      "abbreviation": "OVH",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Overheat",
          "entries": [
            "Once you make an attack with this weapon, it can't be used again to make an attack until the end of your next turn."
            ]
        }
      ]
    },
    {
      "abbreviation": "SPC",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Special",
          "entries": [
            "This weapon deals double damage to bulwark points."
            ]
        }
      ]
    },
    {
      "abbreviation": "SZS",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Small",
          "entries": [
            "This weapon may be mounted in a small hardpoint or greater."
            ]
        }
      ]
    },
    {
      "abbreviation": "SZM",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Medium",
          "entries": [
            "This weapon may be mounted in a medium hardpoint or greater."
            ]
        }
      ]
    },
    {
      "abbreviation": "SZL",
      "source": "SJMAiS",
      "entries": [
        {
          "type": "entries",
          "name": "Large",
          "entries": [
            "This weapon must be mounted in a large hardpoint."
            ]
        }
      ]
    }
  ],
  "item": [
    {
      "name": "Light Ballista",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "SZS"
      ],
      "range": "2500/7500",
      "dmg1": "2d4",
      "dmgType": "P",
      "value": 100000,
      "entries": [
        "These top loaded siege weapons look much like a large crossbow. Unlike some models of ballista which are anchored to the ground at two points, the spelljammer variants have a central reinforced beam on a pivot. The Heavy Ballista makes use of a two-point anchor, but it rests on manually rotating platform that supporting crew can turn to help aim."
      ]
    },
    {
      "name": "Medium Ballista",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "CRW1",
        "SZM"
      ],
      "range": "3000/9000",
      "dmg1": "2d6",
      "dmgType": "P",
      "value": 200000,
      "entries": [
        "These top loaded siege weapons look much like a large crossbow. Unlike some models of ballista which are anchored to the ground at two points, the spelljammer variants have a central reinforced beam on a pivot. The Heavy Ballista makes use of a two-point anchor, but it rests on manually rotating platform that supporting crew can turn to help aim."
      ]
    },
    {
      "name": "Heavy Ballista",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "CRW2",
        "SZL"
      ],
      "range": "3500/10500",
      "dmg1": "2d8",
      "dmgType": "P",
      "value": 400000,
      "entries": [
        "These top loaded siege weapons look much like a large crossbow. Unlike some models of ballista which are anchored to the ground at two points, the spelljammer variants have a central reinforced beam on a pivot. The Heavy Ballista makes use of a two-point anchor, but it rests on manually rotating platform that supporting crew can turn to help aim."
      ]
    },
    {
      "name": "Light Catapult",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "CRW1",
        "FX",
        "SZS"
      ],
      "range": "3500/10500",
      "dmg1": "3d4",
      "dmgType": "B",
      "value": 100000,
      "entries": [
        "A classic siege weapon that uses stored up tension in a single limb to release some projectile at high speeds toward a target. Many traditional catapults have lockable wheels so they can be moved and fired, but the spelljammer variant is built into the hardpoint itself."
      ]
    },
    {
      "name": "Medium Catapult",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "CRW3",
        "FX",
        "SZM"
      ],
      "range": "4000/12000",
      "dmg1": "3d6",
      "dmgType": "B",
      "value": 200000,
      "entries": [
        "A classic siege weapon that uses stored up tension in a single limb to release some projectile at high speeds toward a target. Many traditional catapults have lockable wheels so they can be moved and fired, but the spelljammer variant is built into the hardpoint itself."
      ]
    },
    {
      "name": "Heavy Catapult",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "CRW5",
        "FX",
        "SZL"
      ],
      "range": "4500/13500",
      "dmg1": "3d8",
      "dmgType": "B",
      "value": 400000,
      "entries": [
        "A classic siege weapon that uses stored up tension in a single limb to release some projectile at high speeds toward a target. Many traditional catapults have lockable wheels so they can be moved and fired, but the spelljammer variant is built into the hardpoint itself."
      ]
    },
    {
      "name": "Carronade",
      "source": "SJMAiS",
      "page": 21,
      "type": "SJW",
      "property": [
        "A",
        "BF2",
